// The pure byte transforms, checked against reports the pad actually sent.
//
// fixtures.h is generated by tools/extract_test_fixtures.py out of a btsnoop
// capture under logs/. That matters: these functions encode a reading of the
// DualSense report layout, and a test written from the same reading would agree
// with itself no matter how wrong it was.
#include "check.h"

#include "dualsense/DualSense.h"
#include "dualsense/Transforms.h"
#include "fixtures.h"

#include <cstring>

namespace {

std::span<const uint8_t> report(size_t i)
{
    return {fixtures::input_report[i].data(), fixtures::input_report[i].size()};
}

TEST(captured_reports_are_the_size_the_code_expects)
{
    CHECK_EQ(fixtures::input_report[0].size(),
             size_t{1 + dualsense::INPUT_BT_SIZE});
}

TEST(captured_checksums_verify)
{
    // The pad's own CRC32 over its own bytes. If this fails, every offset the
    // rest of the project relies on is suspect.
    for (size_t i = 0; i < fixtures::INPUT_REPORTS; i++)
        CHECK(transforms::input_crc_is_valid(report(i)));
}

TEST(state_and_opaque_frames_are_told_apart)
{
    // Both kinds share report id 0x31 and both carry a valid CRC. The
    // discriminator is the HasHID flag, and the fixture records which is which
    // straight from the capture.
    for (size_t i = 0; i < fixtures::INPUT_REPORTS; i++)
        CHECK_EQ(transforms::carries_controller_state(report(i)),
                 fixtures::carries_state[i]);
}

TEST(opaque_frames_carry_the_documented_marker)
{
    // Not what the relay keys on any more, but it is what the captures showed,
    // and it should stay true of the ones behind these fixtures.
    for (size_t i = 0; i < fixtures::INPUT_REPORTS; i++)
        if (!fixtures::carries_state[i])
            CHECK_EQ(int(fixtures::input_report[i][transforms::BT_BODY_OFF + 1]),
                     0xd4);
}

TEST(acl_header_packs_handle_and_flag_separately)
{
    // The whole reason this is a function and not BlueZ's macro: a ternary
    // passed as the flag binds looser than the shift, and handle 12 with flag 2
    // came out as 0x000e - handle 14, no flags. An evening went into that.
    CHECK_EQ(transforms::acl_header_handle(12, 0x0002), uint16_t(0x200c));
    CHECK_EQ(transforms::acl_header_handle(12, 0x0000), uint16_t(0x000c));
    CHECK(transforms::acl_header_handle(12, 0x0002) != uint16_t(0x000e));

    // Twelve bits of handle, two of flag, nothing bleeding between them.
    CHECK_EQ(transforms::acl_header_handle(0x0fff, 0x0002), uint16_t(0x2fff));
    CHECK_EQ(transforms::acl_header_handle(0x1234, 0x0002), uint16_t(0x2234));
}

TEST(cut_down_report_keeps_the_fields_the_console_reads)
{
    const auto &src = fixtures::input_report[0];
    const auto basic = transforms::make_cut_down_report(report(0));
    const uint8_t *b = &src[transforms::BT_BODY_OFF];

    CHECK_EQ(basic.size(), dualsense::INPUT_BT_BASIC_SIZE);
    CHECK_EQ(int(basic[0]), int(dualsense::REPORT_INPUT_BT_BASIC));
    for (size_t i = 0; i < 4; i++)
        CHECK_EQ(int(basic[1 + i]), int(b[i]));            // sticks
    CHECK_EQ(int(basic[5]), int(b[transforms::FACE_BUTTON_OFF]));
    CHECK_EQ(int(basic[8]), int(b[4]));                    // triggers
    CHECK_EQ(int(basic[9]), int(b[5]));

    // The third button byte is not a straight copy: PS and touchpad in the low
    // bits, the counter from a separate field of the full report above them.
    // Sending it as zero gives a controller whose counter never moves.
    CHECK_EQ(int(basic[7]), int((b[9] & 0x03) | uint8_t((b[6] & 0x3f) << 2)));
}

TEST(usb_report_reframes_the_same_body)
{
    const auto &src = fixtures::input_report[0];
    const auto usb = transforms::make_usb_report(report(0));

    CHECK_EQ(usb.size(), dualsense::INPUT_USB_SIZE);
    CHECK_EQ(int(usb[0]), int(dualsense::REPORT_INPUT_USB));

    // The 63-byte body is carried across unchanged except for the status byte,
    // whose charging nibble is forced (see the test below). Copying from the
    // seq_tag instead would shift every axis and button by one, which is the
    // bug this pins down - so compare byte for byte around the one exception.
    for (size_t i = 0; i < dualsense::INPUT_BODY_LEN; i++) {
        if (i == dualsense::STATUS_OFF)
            continue;
        CHECK_EQ(int(usb[dualsense::INPUT_BODY_OFF_USB + i]),
                 int(src[transforms::BT_BODY_OFF + i]));
    }
    // And the axes really are at the front, not one byte along.
    CHECK_EQ(int(usb[dualsense::INPUT_BODY_OFF_USB]),
             int(src[transforms::BT_BODY_OFF]));
}

TEST(the_ps_bit_is_the_one_the_console_watches)
{
    // The pair command was timed against the pad's three button bytes going
    // 08 00 00 -> 08 00 01. This fixture is a report with nothing pressed, and
    // it carries exactly the first of those, which is what pins BUTTON_PS_OFF
    // to the byte the measurement was read from.
    const auto &src = fixtures::input_report[0];
    CHECK_EQ(int(src[transforms::BT_BODY_OFF + transforms::FACE_BUTTON_OFF]), 0x08);
    CHECK_EQ(int(src[transforms::BT_BODY_OFF + transforms::FACE_BUTTON_OFF + 1]), 0x00);
    CHECK_EQ(int(src[transforms::BT_BODY_OFF + transforms::BUTTON_PS_OFF]), 0x00);

    auto usb = transforms::make_usb_report(report(0));
    const auto before = usb;
    CHECK_EQ(int(usb[dualsense::INPUT_BODY_OFF_USB + transforms::BUTTON_PS_OFF]
                 & transforms::BUTTON_PS), 0);

    transforms::set_ps_on_usb_report(usb);
    CHECK_EQ(int(usb[dualsense::INPUT_BODY_OFF_USB + transforms::BUTTON_PS_OFF]
                 & transforms::BUTTON_PS), int(transforms::BUTTON_PS));

    // One bit and nothing else: over USB there is no checksum to re-stamp, so a
    // second difference anywhere would be a bug rather than an update.
    for (size_t i = 0; i < usb.size(); i++) {
        if (i == dualsense::INPUT_BODY_OFF_USB + transforms::BUTTON_PS_OFF)
            continue;
        CHECK_EQ(int(usb[i]), int(before[i]));
    }
}

TEST(usb_report_forces_the_charging_nibble_and_keeps_the_capacity)
{
    std::array<uint8_t, 1 + dualsense::INPUT_BT_SIZE> r = fixtures::input_report[0];
    uint8_t &status = r[transforms::BT_BODY_OFF + dualsense::STATUS_OFF];

    status = (dualsense::STATUS_CHARGING_DISCHARGING << 4) | 7;
    auto usb = transforms::make_usb_report(std::span<const uint8_t>(r));
    uint8_t out = usb[dualsense::INPUT_BODY_OFF_USB + dualsense::STATUS_OFF];
    CHECK_EQ(int(out & 0x0f), 7);                                  // capacity through
    CHECK_EQ(int(out >> 4), int(dualsense::STATUS_CHARGING_CHARGING));

    status = (dualsense::STATUS_CHARGING_DISCHARGING << 4) | 10;
    usb = transforms::make_usb_report(std::span<const uint8_t>(r));
    out = usb[dualsense::INPUT_BODY_OFF_USB + dualsense::STATUS_OFF];
    CHECK_EQ(int(out >> 4), int(dualsense::STATUS_CHARGING_FULL));  // full reads full
}

TEST(transforms_refuse_a_report_of_the_wrong_size)
{
    const std::array<uint8_t, 20> stub{};
    CHECK(!transforms::input_crc_is_valid(std::span<const uint8_t>(stub)));
    CHECK(!transforms::carries_controller_state(std::span<const uint8_t>(stub)));
}

}  // namespace
