#!/usr/bin/env python3
"""Pull real DualSense reports out of a btsnoop capture into a C++ fixture header.

The pure functions in Transforms.h and DualSense.h are worth testing precisely
because they can be checked against bytes the pad actually sent, rather than
against bytes we invented to match our own understanding. This lifts a handful
of those out of logs/*.dump so the tests carry evidence rather than guesses.
"""
import struct, sys, zlib

BTSNOOP_HDR = 16
REC_HDR = 24


def records(path):
    with open(path, 'rb') as f:
        hdr = f.read(BTSNOOP_HDR)
        if hdr[:8] != b'btsnoop\x00':
            sys.exit(f'{path}: not a btsnoop capture')
        while True:
            rh = f.read(REC_HDR)
            if len(rh) < REC_HDR:
                return
            _orig, incl, flags, _drops, _ts = struct.unpack('>IIIIq', rh)
            data = f.read(incl)
            if len(data) < incl:
                return
            yield flags, data


def input_reports(path, want):
    """79-byte 0xa1 0x31 payloads carried on an L2CAP interrupt channel.

    Both kinds are wanted: frames carrying controller state, and frames of the
    pad's opaque stream that share the report id. A test that only ever sees
    one of them cannot show that the two are told apart.
    """
    state, opaque = [], []
    for _flags, d in records(path):
        if len(d) < 9 or d[0] != 0x02:          # H4: ACL only
            continue
        dlen = struct.unpack_from('<H', d, 3)[0]
        if 5 + dlen > len(d):
            continue
        l2len, _cid = struct.unpack_from('<HH', d, 5)
        payload = d[9:9 + l2len]
        if len(payload) != l2len or l2len != 79:
            continue
        if payload[0] != 0xa1 or payload[1] != 0x31:
            continue
        bucket = state if (payload[2] & 0x01) else opaque
        if payload not in bucket and len(bucket) < want:
            bucket.append(payload)
        if len(state) >= want and len(opaque) >= want:
            break
    return state + opaque


def crc32_seeded(seed, data):
    return zlib.crc32(data, zlib.crc32(bytes([seed]))) & 0xffffffff


def other_reports(path, want=3):
    """Feature answers (0xa3, CRC seed 0xa3) and output reports (0xa2, seed 0xa2).

    Neither had any test coverage: the input path was the only one with
    fixtures, so the two other checksum seeds and the feature size table were
    taken on trust.
    """
    feats, outs = {}, []
    for _flags, d in records(path):
        if len(d) < 9 or d[0] != 0x02:
            continue
        dlen = struct.unpack_from('<H', d, 3)[0]
        if 5 + dlen > len(d):
            continue
        l2len, _cid = struct.unpack_from('<HH', d, 5)
        p = d[9:9 + l2len]
        if len(p) != l2len or len(p) < 6:
            continue
        tail = struct.unpack_from('<I', p, len(p) - 4)[0]
        if p[0] == 0xa3 and p[1] not in feats:
            if crc32_seeded(0xa3, p[1:-4]) == tail:
                feats[p[1]] = p
        elif p[0] == 0xa2 and p[1] == 0x31 and len(outs) < want:
            if crc32_seeded(0xa2, p[1:-4]) == tail:
                outs.append(p)
        if len(feats) >= 6 and len(outs) >= want:
            break
    return feats, outs


def emit_blob(w, name, data):
    w(f'inline constexpr std::array<uint8_t, {len(data)}> {name} = {{{{')
    w(', '.join(f'0x{b:02x}' for b in data))
    w('}};\n')


def emit(reports, feats, outs, out):
    w = out.write
    w('// Generated by tools/extract_test_fixtures.py - do not edit.\n')
    w('//\n')
    w('// Real DualSense input reports, lifted out of a btsnoop capture so the\n')
    w('// transforms are checked against bytes the pad actually sent.\n')
    w('#pragma once\n#include <array>\n#include <cstdint>\n\n')
    w('namespace fixtures {\n\n')
    w('// [0xa1][0x31][seq_tag][body 63][pad 9][crc32 4]\n')
    w(f'inline constexpr size_t INPUT_REPORTS = {len(reports)};\n')
    w('inline constexpr std::array<std::array<uint8_t, 79>, '
      f'{len(reports)}> input_report = {{{{\n')
    for r in reports:
        w('    {')
        w(', '.join(f'0x{b:02x}' for b in r))
        w('},\n')
    w('}};\n\n')
    # Record what each one is, so a failing test says something.
    w('// HasHID (flags bit 0) says the frame carries controller state rather\n')
    w('// than a frame of the pad\'s opaque stream.\n')
    w('inline constexpr std::array<bool, '
      f'{len(reports)}> carries_state = {{{{ ')
    w(', '.join('true' if (r[2] & 0x01) else 'false' for r in reports))
    w(' }};\n\n')

    # Feature answers: [0xa3][id][body...][crc32], seed 0xa3. The declared body
    # length is what feature_report_size() must agree with.
    w('// Feature answers as the pad sent them: [0xa3][id][body][crc32].\n')
    w(f'inline constexpr size_t FEATURE_REPORTS = {len(feats)};\n')
    for rid, blob in sorted(feats.items()):
        emit_blob(w, f'feature_{rid:02x}', blob)
    w('\ninline constexpr std::array<uint8_t, '
      f'{len(feats)}> feature_ids = {{{{ ')
    w(', '.join(f'0x{r:02x}' for r in sorted(feats)))
    w(' }};\n')
    w('inline constexpr std::array<size_t, '
      f'{len(feats)}> feature_body_len = {{{{ ')
    w(', '.join(str(len(feats[r]) - 1) for r in sorted(feats)))
    w(' }};\n\n')

    # Output reports the console sent: [0xa2][0x31][seq][tag][common...][crc32].
    w('// An output report on the wire: [0xa2][0x31][seq_tag][tag][body][crc32].\n')
    for i, blob in enumerate(outs):
        emit_blob(w, f'output_report_{i}', blob)
    w(f'\ninline constexpr size_t OUTPUT_REPORTS = {len(outs)};\n\n')

    w('}  // namespace fixtures\n')


if __name__ == '__main__':
    cap = sys.argv[1]
    want = int(sys.argv[2]) if len(sys.argv) > 2 else 8
    reps = input_reports(cap, want)
    if not reps:
        sys.exit(f'{cap}: no 79-byte 0x31 input reports found')
    # Prove the checksum understanding on the way past.
    for r in reps:
        theirs = struct.unpack_from('<I', r, 75)[0]
        ours = crc32_seeded(r[0], r[1:75])
        assert theirs == ours, f'CRC mismatch on a captured report: {theirs:08x} != {ours:08x}'
    feats, outs = other_reports(cap)
    with open('tests/fixtures.h', 'w') as f:
        emit(reps, feats, outs, f)
    print(f'{cap} -> tests/fixtures.h: '
          f'{sum(1 for r in reps if r[2] & 1)} state, '
          f'{sum(1 for r in reps if not r[2] & 1)} opaque, '
          f'{len(feats)} feature, {len(outs)} output')
